Add userCameraCap (BBB 2.4.5)
littleredbutton/bigbluebutton-api-php pull request #113
Opened 2022-03-15 14:44 UTC by SamuelWei

Implements #112

2022-03-15 14:51 UTC, SamuelWei commented
@sualko After or before implementing this, we can think about releasing a new minor version (see my release draft).
As #109 is not effecting the feature support of the api, we could independently make the release decision.

As soon as BBB 2.5 is released we also have to make some changes to this library. I'll create issues and PR soon.

2022-03-15 21:50 UTC, FelixJacobi requested changes
Looks fine to me otherwhise.

2022-03-15 21:50 UTC, FelixJacobi commented on src/Parameters/CreateMeetingParameters.php
> +    public function isUserCameraCapDisabled()
```suggestion
    public function isUserCameraCapDisabled(): bool
```

2022-03-15 21:50 UTC, FelixJacobi commented on src/Parameters/CreateMeetingParameters.php
> +    public function disableUserCameraCap()
```suggestion
    public function disableUserCameraCap(): self
```

2022-03-15 21:50 UTC, FelixJacobi commented on tests/unit/Parameters/CreateMeetingParametersTest.php
> +    public function testUserCameraCap()
```suggestion
    public function testUserCameraCap(): void
```

2022-03-16 12:12 UTC, FelixJacobi approved these changes

2022-03-16 12:13 UTC, merged