Support multiple checksum algorithms
littleredbutton/bigbluebutton-api-php pull request #147
Opened 2022-10-22 14:47 UTC by SamuelWei

Fixes #146 

**Changes**
- Adding hash algorithm to the constructor as the fourth optional argument
-  Adjust tests

2022-10-26 16:37 UTC, sualko approved these changes
Looks good.

2022-10-26 16:38 UTC, SamuelWei commented
> Looks good.

@sualko Can you just have a quick look into the linked issue, as I started a question on how to deal with it. This is just one implementation idea

2022-11-02 17:49 UTC, FelixJacobi requested changes

2022-11-02 17:49 UTC, FelixJacobi commented on src/BigBlueButton.php
> +    public function __construct(?string $baseUrl = null, ?string $secret = null, ?TransportInterface $transport = null, ?string $hashAlgorithm = 'sha1')
```suggestion
    public function __construct(?string $baseUrl = null, ?string $secret = null, ?TransportInterface $transport = null, string $hashAlgorithm = 'sha1')
```

It does not make sense to allow `null` here.

2023-08-31 06:38 UTC, SamuelWei commented
Changed the initial implementation using a 4th constructor argument to a fluent setter to be compliant with the official PHP API

2023-10-01 12:02 UTC, FelixJacobi commented
> Changed the initial implementation using a 4th constructor argument to a fluent setter to be compliant with the official PHP API

Hm, I was fine with the initial implementation,  except the type hint 😄  . In my opinion, setters, which changes the behavior of the object are bad at all. Imagine the following use case: A developer to knowing the internals of this library injects the object using dependency injection in his own class and just thinks it's a good idea to just set the algorithm. This changes the state aferwards permanently and globally. As the algorithm is a connection parameter like the URL and secret, I would not allow changing it after setting it in the constructor.

2023-10-06 11:46 UTC, SamuelWei commented
@FelixJacobi I reverted it back to the original initial implementation

2023-10-07 15:42 UTC, FelixJacobi approved these changes

2023-10-07 15:44 UTC, merged