Implement API changes in BBB 2.4-2.6
littleredbutton/bigbluebutton-api-php pull request #156
Opened 2023-08-31 07:19 UTC by SamuelWei

Fixes #150

2024-02-08 20:21 UTC, FelixJacobi requested changes
Looks fine to me, some small suggestions.

2024-02-08 20:21 UTC, FelixJacobi commented on src/Parameters/JoinMeetingParameters.php
> +    public function __construct(string $meetingID, string $fullName, $passwordOrRole = null)
Since we cannot use Union types yet, we must check types here manually.

2024-02-08 20:21 UTC, FelixJacobi commented on src/Parameters/JoinMeetingParameters.php
> +            @trigger_error(sprintf('Passing $passwordOrRole parameter to constructor of "%s" is deprecated since 5.1 and will be removed in 6.0. Use "%s::setRole()" to set the designated role for the
This is missing an instanceof check for Role. I personally would keep the parameter for roles only in the next major version as it is mandatory IIRC.

2024-02-08 20:21 UTC, FelixJacobi commented on tests/unit/Responses/GetMeetingInfoResponseTest.php
> +class GetMeetingInfoResponseTest extends BigBlueButton\TestCase
When on track: Adding `final` here? :) (same for the other tests)

2024-02-09 09:45 UTC, SamuelWei commented
@FelixJacobi 
Following this and #16, should release 5.1 and start with the changes for 6.0 ?

2024-02-09 10:16 UTC, FelixJacobi approved these changes

2024-02-09 10:16 UTC, merged

2024-02-09 10:16 UTC, FelixJacobi commented
> @FelixJacobi Following this and #164 , should release 5.1 and start with the changes for 6.0 ?

Yes. Please keep in mind: In 6.0, only deprecations must be removed, no new features must be added.