add isDuplicate helper for create response
littleredbutton/bigbluebutton-api-php pull request #45
Opened 2020-09-22 11:42 UTC by sualko

I think we should add helper functions for all message keys, or at least add the key as const to the corresponding class.

2021-01-28 15:36 UTC, sualko commented
I think it make sense to merge this after #49. The following keys are missing:

create: idNotUnique
join: successfullyJoined, InvalidSession, BigBlueButtonServerError, guestDeny
end: sentEndMeetingRequest
putRecordingTextTrackAnchor: upload_text_track_success, upload_text_track_failed, empty_uploaded_text_track, paramError
deleteRecording: InvalidRecordingId
getRecordings: noRecordings

It's not clear if this list is complete, since BBB did not document them and the are not using one general const file, map or similar :see_no_evil:

2021-03-01 09:46 UTC, SamuelWei requested changes

2021-03-01 09:46 UTC, SamuelWei commented on src/Responses/CreateMeetingResponse.php
> +    public function isDuplicate()
what about idNotUnique?

2021-03-01 09:46 UTC, SamuelWei commented on src/Responses/DeleteRecordingsResponse.php
> +    const KEY_INVALID_ID = 'InvalidRecordingId';
what about a method like isDuplicate() ?

2021-03-01 09:46 UTC, SamuelWei commented on src/Responses/EndMeetingResponse.php
> +    const KEY_SET_END_MEETING_REQUEST = 'sentEndMeetingRequest';
what about a method like isDuplicate() ?

2021-03-01 09:46 UTC, SamuelWei commented on src/Responses/GetRecordingsResponse.php
> +    const KEY_NO_RECORDINGS = 'noRecordings';
what about a method like isDuplicate() ?

2021-03-01 09:46 UTC, SamuelWei commented on src/Responses/JoinMeetingResponse.php
> +    const KEY_SUCCESSFULLY_JOINED = 'successfullyJoined';
what about a methods like isDuplicate() ?

2021-03-01 09:46 UTC, SamuelWei commented on src/Responses/JoinMeetingResponse.php
> +    const KEY_GUEST_DENY          = ' guestDeny';
is there a space too much?

2021-03-01 09:46 UTC, SamuelWei commented on src/Responses/PutRecordingTextTrackResponse.php
> +    const KEY_SUCCESS     = 'upload_text_track_success';
what about a methods like isDuplicate() ?

2021-03-01 09:46 UTC, SamuelWei commented on src/Responses/PutRecordingTextTrackResponse.php
> +    const KEY_PARAM_ERROR = 'paramError';
I think a global list of messageKeys in BBB would have prevented this naming scheme chaos

2021-03-01 10:16 UTC, sualko commented
I did not add those helper functions, because I'm not sure if this is really helping anyone. That's something we should be discuss :smile:

2021-03-09 14:01 UTC, SamuelWei commented on src/Responses/JoinMeetingResponse.php
> +    const KEY_GUEST_DENY          = ' guestDeny';
@sualko ?

2021-03-09 14:02 UTC, SamuelWei commented
> I did not add those helper functions, because I'm not sure if this is really helping anyone. That's something we should be discuss 😄

I guess you are right, most people would not use it. The only question would be should we add it to have a more equal api behavior or not.

2021-03-09 14:10 UTC, sualko commented on src/Responses/JoinMeetingResponse.php
> +    const KEY_GUEST_DENY          = ' guestDeny';
I think you are right.

2021-03-11 09:52 UTC, SamuelWei commented
> > The only question would be should we add it to have a more equal api behavior or not.
> 
> We could also remove the one I added 😄

If you would remove it, what would be the sence of this PR?

2021-03-11 10:13 UTC, sualko commented
> If you would remove it, what would be the sence of this PR?

We would still have all those keys, which are very important from my pov.

2021-03-11 10:45 UTC, SamuelWei commented
> > If you would remove it, what would be the sence of this PR?
> 
> We would still have all those keys, which are very important from my pov.

I added some helpers, please let me know if you like the naming

2021-03-11 11:11 UTC, sualko commented
Great work. Looks good.

2021-04-09 07:31 UTC, SamuelWei approved these changes

2021-04-09 07:32 UTC, merged