Merge upstream
littleredbutton/bigbluebutton-api-php pull request #88
Opened 2021-06-25 12:58 UTC by sualko

2021-07-02 23:25 UTC, FelixJacobi requested changes
Looks fine for me except for the type hints.

2021-07-02 23:25 UTC, FelixJacobi commented on src/Core/Meeting.php
> +    public function getModerators()
```suggestion
    public function getModerators(): array
```

I guess we should add return type hints when pulling upstream changes and their miss them. As our library has an independent release schedule and you must decide to use it, I guess that is not a big problem.

2021-07-02 23:25 UTC, FelixJacobi commented on src/Core/Meeting.php
> +    public function getViewers()
```suggestion
    public function getViewers(): array
```

2021-07-02 23:25 UTC, FelixJacobi commented on tests/unit/Responses/GetMeetingInfoResponseTest.php
> +    public function testMeetingModerators()
```suggestion
    public function testMeetingModerators(): void
```

2021-07-02 23:25 UTC, FelixJacobi commented on tests/unit/Responses/GetMeetingInfoResponseTest.php
> +    public function testMeetingViewers()
```suggestion
    public function testMeetingViewers(): void
```

2021-07-03 15:10 UTC, sualko commented
I added all your suggested type hints in one commit.

2021-07-03 15:25 UTC, sualko commented
@SamuelWei @FelixJacobi we can include this in 4.0, right?

2021-07-04 00:08 UTC, FelixJacobi commented
> @SamuelWei @FelixJacobi we can include this in 4.0, right?

In think so :) .

2021-07-04 00:10 UTC, FelixJacobi approved these changes

2021-07-04 00:10 UTC, merged